describe("Audio", function()  
  describe("SquareWaveGenerator", function()
    setup(function()
      SquareWaveGenerator = require("gameboy/audio/square_wave_generator")
    end)
    it("can be created", function()
      square = SquareWaveGenerator:new()
      assert.are_not_same(square, nil)
    end)
    it("waveform can be set", function()
      local square = SquareWaveGenerator:new()
      square:setWaveform(0x0F)
      assert.are_same(square:waveform(), 0x0F)
    end)
    it("output is based on the low bit of the selected waveform", function()
      local square = SquareWaveGenerator:new()
      square:setWaveform(0x0F)
      assert.are_same(square:output(), 1)
      square:setWaveform(0xF0)
      assert.are_same(square:output(), 0)
    end)
    it("clocks rotate the waveform", function()
      local square = SquareWaveGenerator:new()
      square:setWaveform(0x01)
      square:clock()
      assert.are_same(square:waveform(), 0x80)
      square:clock()
      assert.are_same(square:waveform(), 0x40)
    end)
    it("the waveform is clocked when the timer expires", function()
      local square = SquareWaveGenerator:new()
      square:setWaveform(0x01)
      square.timer:reload(10)
      square.timer:advance(10)
      assert.are_same(square:waveform(), 0x80)
    end)
  end)
end)